version: "3.9"

services:

  goldendrop_server:
    container_name: goldendrop-app-server
    image: techbuddy24/goldendrop:app-server
    ports:
      - "8080:8080"
    networks:
      - techbuddy-network

  goldendrop_server_ui:
    container_name: goldendrop-app-server-ui
    image: techbuddy24/goldendrop:app-server-ui
    ports:
      - "3000:80"
    networks:
      - techbuddy-network

  # goldendrop_load_balancer:
  #   container_name: goldendrop-load-balancer


networks:
  techbuddy-network:
    driver: bridge