RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
RewriteCond %{REQUEST_URI} "^/$"
RewriteRule .* http://dev.alwaystech.com/ui/ [L,R=301]

RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
RewriteCond %{REQUEST_URI} "^/ui"
RewriteRule .* http://host.docker.internal:3000%{REQUEST_URI} [P]

RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
RewriteCond %{REQUEST_URI} "^/ui/"
RewriteRule .* http://host.docker.internal:3000%{REQUEST_URI} [P]

RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
RewriteCond %{REQUEST_URI} ^(.+\.(jpg|jpeg|png|js|tsx|css|mjs|ts|scss|svg|ico))$
RewriteRule .* http://host.docker.internal:3000%{REQUEST_URI} [L,P]

RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
RewriteRule .* http://host.docker.internal:8080%{REQUEST_URI} [P]

Header add x-app-version "0.0.0"

Timeout 600s
