Listen 443

SSLCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES
SSLProxyCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES

SSLHonorCipherOrder on

SSLProtocol all -SSLv3
SSLProxyProtocol all -SSLv3

<VirtualHost *:443>
    DocumentRoot "/usr/local/apache2/htdocs"
    ServerName onprem.example.com:443
    ServerAdmin admin@alwaystech.com
    SSLCertificateFile "/usr/local/apache2/ssl/server.crt"
    SSLCertificateKeyFile "/usr/local/apache2/ssl/server.key"
    
    RewriteEngine On

    # SetEnvIf Origin "https://(dev.alwaystech.com)$" ORIGIN=$0
    # Header set Access-Control-Allow-Origin %{ORIGIN}e env=ORIGIN
    # Header set Access-Control-Allow-Credentials "true" env=ORIGIN
    # Header merge Vary Origin

    RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
    RewriteCond %{REQUEST_URI} "^/$"
    RewriteRule .* http://dev.alwaystech.com/ui/ [L,R=301]

    RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
    RewriteCond %{REQUEST_URI} "^/ui"
    RewriteRule .* http://host.docker.internal:3000%{REQUEST_URI} [P]

    RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
    RewriteCond %{REQUEST_URI} "^/ui/"
    RewriteRule .* http://host.docker.internal:3000%{REQUEST_URI} [P]

    RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
    RewriteCond %{REQUEST_URI} ^(.+\.(jpg|jpeg|png|js|tsx|css|mjs|ts|scss|svg|ico))$
    RewriteRule .* http://host.docker.internal:3000%{REQUEST_URI} [L,P]

    RewriteCond %{HTTP_HOST} "dev.alwaystech.com"
    RewriteRule .* http://host.docker.internal:8080%{REQUEST_URI} [P]

</VirtualHost>
